const FILLER_WORDS = new Set([
  'a',
  'an',
  'assistant',
  'boss',
  'can',
  'commander',
  'could',
  'do',
  'for',
  'hey',
  'jarvis',
  'just',
  'kindly',
  'master',
  'me',
  'mind',
  'my',
  'please',
  'pls',
  'sir',
  'the',
  'this',
  'to',
  'what',
  'is',
  'are',
  'was',
  'were',
  'would',
  'you'
]);

const LEAD_IN_PATTERNS = [
  /^(?:please\s+)+/i,
  /^(?:can|could|would|will)\s+you\s+/i,
  /^(?:would\s+you\s+mind\s+)+/i,
  /^(?:i\s+need\s+you\s+to|i\s+want\s+you\s+to)\s+/i,
  /^(?:hey\s+)?(?:jarvis|assistant)\s+/i
];

const PHRASE_REPLACEMENTS = [
  { from: /\bturn it up\b/g, to: 'increase volume' },
  { from: /\bturn it down\b/g, to: 'decrease volume' },
  { from: /\bmake it louder\b/g, to: 'increase volume' },
  { from: /\bmake it quieter\b/g, to: 'decrease volume' },
  { from: /\bmake it brighter\b/g, to: 'increase brightness' },
  { from: /\bmake it dimmer\b/g, to: 'decrease brightness' },
  { from: /\bshut down\b/g, to: 'shutdown' },
  { from: /\blook for\b/g, to: 'find' },
  { from: /\bopen up\b/g, to: 'open' },
  { from: /\bput on\b/g, to: 'play' },
  { from: /\bstart playing\b/g, to: 'play' },
  { from: /\bplay me\b/g, to: 'play' },
  { from: /\bqueue up\b/g, to: 'play' },
  { from: /\bfull screen\b/g, to: 'fullscreen' },
  { from: /\bminimise\b/g, to: 'minimize' },
  { from: /\bmaximise\b/g, to: 'maximize' },
  { from: /\bunpause\b/g, to: 'resume' },
  { from: /\bcarry on\b/g, to: 'resume' },
  { from: /\bnexr\b/g, to: 'next' },
  { from: /\bsony\b/g, to: 'song' }
];

const DOMAIN_VOCABULARY = [
  'alarm',
  'application',
  'app',
  'battery',
  'brightness',
  'browser',
  'calendar',
  'chrome',
  'clock',
  'close',
  'copy',
  'cpu',
  'create',
  'delete',
  'desktop',
  'directory',
  'disk',
  'documents',
  'downloads',
  'edge',
  'erase',
  'excel',
  'file',
  'find',
  'folder',
  'google',
  'help',
  'launch',
  'lock',
  'memory',
  'minimize',
  'move',
  'music',
  'mute',
  'navigate',
  'notepad',
  'open',
  'outlook',
  'paint',
  'pictures',
  'processes',
  'ram',
  'remind',
  'reminder',
  'remove',
  'rename',
  'restart',
  'run',
  'search',
  'settings',
  'shutdown',
  'sleep',
  'spotify',
  'status',
  'switch',
  'teams',
  'timer',
  'unmute',
  'url',
  'videos',
  'volume',
  'website',
  'window',
  'word',
  'youtube',
  'zoom',
  'queue',
  'play',
  'song',
  'songs',
  'music',
  'track',
  'tracks',
  'media',
  'playback',
  'next',
  'previous',
  'prev',
  'pause',
  'resume',
  'skip',
  'continue',
  'unpause',
  'fullscreen',
  'full',
  'screen',
  'watch'
];

module.exports = {
  DOMAIN_VOCABULARY,
  FILLER_WORDS,
  LEAD_IN_PATTERNS,
  PHRASE_REPLACEMENTS
};
