const FILLER_WORDS = new Set([
  'a',
  'actually',
  'an',
  'assistant',
  'basically',
  'boss',
  'can',
  'commander',
  'could',
  'do',
  'for',
  'hey',
  'jarvis',
  'just',
  'kindly',
  'literally',
  'master',
  'me',
  'mind',
  'my',
  'now',
  'please',
  'pls',
  'sir',
  'simply',
  'the',
  'this',
  'to',
  'uh',
  'um',
  'what',
  'is',
  'are',
  'was',
  'were',
  'would',
  'you'
]);

const LEAD_IN_PATTERNS = [
  /^(?:please\s+)+/i,
  /^(?:can|could|would|will)\s+you\s+/i,
  /^(?:can|could|would|will)\s+you\s+(?:please\s+)?(?:go\s+ahead\s+and\s+)?/i,
  /^(?:would\s+you\s+mind\s+)+/i,
  /^(?:i\s+need\s+you\s+to|i\s+want\s+you\s+to)\s+/i,
  /^(?:go\s+ahead\s+and|kindly|just)\s+/i,
  /^(?:hey\s+)?(?:jarvis|assistant)\s+/i
];

const PHRASE_REPLACEMENTS = [
  { from: /\bturn it up\b/g, to: 'increase volume' },
  { from: /\bturn it down\b/g, to: 'decrease volume' },
  { from: /\bmake it louder\b/g, to: 'increase volume' },
  { from: /\bmake volume louder\b/g, to: 'increase volume' },
  { from: /\braise volume\b/g, to: 'increase volume' },
  { from: /\bvolume higher\b/g, to: 'increase volume' },
  { from: /\bmake it quieter\b/g, to: 'decrease volume' },
  { from: /\blower volume\b/g, to: 'decrease volume' },
  { from: /\bvolume lower\b/g, to: 'decrease volume' },
  { from: /\bmake it brighter\b/g, to: 'increase brightness' },
  { from: /\braise brightness\b/g, to: 'increase brightness' },
  { from: /\bbrightness higher\b/g, to: 'increase brightness' },
  { from: /\bmake it dimmer\b/g, to: 'decrease brightness' },
  { from: /\blower brightness\b/g, to: 'decrease brightness' },
  { from: /\bbrightness lower\b/g, to: 'decrease brightness' },
  { from: /\bshut down\b/g, to: 'shutdown' },
  { from: /\bclose down\b/g, to: 'close' },
  { from: /\bexit out of\b/g, to: 'close' },
  { from: /\bget rid of\b/g, to: 'close' },
  { from: /\blook for\b/g, to: 'find' },
  { from: /\bopen up\b/g, to: 'open' },
  { from: /\bbring up\b/g, to: 'open' },
  { from: /\bpull up\b/g, to: 'open' },
  { from: /\bfire up\b/g, to: 'open' },
  { from: /\bbring to front\b/g, to: 'switch to' },
  { from: /\bswitch over to\b/g, to: 'switch to' },
  { from: /\bput on\b/g, to: 'play' },
  { from: /\bstart playing\b/g, to: 'play' },
  { from: /\bplay me\b/g, to: 'play' },
  { from: /\bqueue up\b/g, to: 'play' },
  { from: /\bfull screen\b/g, to: 'fullscreen' },
  { from: /\bminimise\b/g, to: 'minimize' },
  { from: /\bmaximise\b/g, to: 'maximize' },
  { from: /\bunpause\b/g, to: 'resume' },
  { from: /\bcarry on\b/g, to: 'resume' },
  { from: /\bnexr\b/g, to: 'next' },
  { from: /\bsony\b/g, to: 'song' },
  { from: /\bweb site\b/g, to: 'website' }
];

const TOKEN_CORRECTIONS = {
  activte: 'activate',
  apllication: 'application',
  applcation: 'application',
  brighness: 'brightness',
  calender: 'calendar',
  calenders: 'calendars',
  cloe: 'close',
  clos: 'close',
  cloth: 'close',
  clothes: 'close',
  cloze: 'close',
  clsoe: 'close',
  crome: 'chrome',
  crom: 'chrome',
  decrese: 'decrease',
  discordd: 'discord',
  documants: 'documents',
  dowloads: 'downloads',
  exitt: 'exit',
  firefix: 'firefox',
  foldr: 'folder',
  increse: 'increase',
  lauch: 'launch',
  lnauch: 'launch',
  mesage: 'message',
  mozila: 'mozilla',
  notpad: 'notepad',
  opne: 'open',
  playbak: 'playback',
  rose: 'close',
  seach: 'search',
  spoitfy: 'spotify',
  swtich: 'switch',
  teems: 'teams',
  volum: 'volume',
  whatsap: 'whatsapp',
  youtub: 'youtube',
  chrmoe: 'chrome'
};

const TOKEN_SEQUENCE_REPLACEMENTS = [
  { from: ['what', 'sap'], to: ['whatsapp'] },
  { from: ['what', 'sapp'], to: ['whatsapp'] },
  { from: ['you', 'tube'], to: ['youtube'] },
  { from: ['micro', 'soft'], to: ['microsoft'] }
];

const DOMAIN_VOCABULARY = [
  'alarm',
  'application',
  'app',
  'battery',
  'brightness',
  'browser',
  'calendar',
  'chrome',
  'clock',
  'close',
  'copy',
  'cpu',
  'create',
  'delete',
  'desktop',
  'directory',
  'disk',
  'documents',
  'downloads',
  'edge',
  'erase',
  'excel',
  'file',
  'find',
  'folder',
  'google',
  'help',
  'launch',
  'lock',
  'memory',
  'minimize',
  'move',
  'music',
  'mute',
  'navigate',
  'notepad',
  'open',
  'outlook',
  'paint',
  'pictures',
  'processes',
  'ram',
  'remind',
  'reminder',
  'remove',
  'rename',
  'restart',
  'run',
  'search',
  'settings',
  'shutdown',
  'sleep',
  'spotify',
  'status',
  'switch',
  'teams',
  'timer',
  'unmute',
  'url',
  'videos',
  'volume',
  'website',
  'window',
  'word',
  'youtube',
  'zoom',
  'queue',
  'play',
  'song',
  'songs',
  'music',
  'track',
  'tracks',
  'media',
  'playback',
  'next',
  'previous',
  'prev',
  'pause',
  'resume',
  'skip',
  'continue',
  'unpause',
  'fullscreen',
  'full',
  'screen',
  'watch'
];

module.exports = {
  DOMAIN_VOCABULARY,
  FILLER_WORDS,
  LEAD_IN_PATTERNS,
  PHRASE_REPLACEMENTS,
  TOKEN_CORRECTIONS,
  TOKEN_SEQUENCE_REPLACEMENTS
};
