const FILLER_WORDS = new Set([
  'a',
  'actually',
  'an',
  'assistant',
  'before',
  'basically',
  'boss',
  'but',
  'can',
  'commander',
  'could',
  'do',
  'during',
  'for',
  'hey',
  'i',
  'jarvis',
  'just',
  'kindly',
  'literally',
  'maybe',
  'master',
  'me',
  'mind',
  'my',
  'now',
  'okay',
  'ok',
  'please',
  'pls',
  'saying',
  'sir',
  'simply',
  'so',
  'talking',
  'the',
  'this',
  'to',
  'uh',
  'um',
  'while',
  'what',
  'is',
  'are',
  'was',
  'were',
  'would',
  'you'
]);

const LEAD_IN_PATTERNS = [
  /^(?:please\s+)+/i,
  /^(?:can|could|would|will)\s+you\s+/i,
  /^(?:can|could|would|will)\s+you\s+(?:please\s+)?(?:go\s+ahead\s+and\s+)?/i,
  /^(?:would\s+you\s+mind\s+)+/i,
  /^(?:i\s+need\s+you\s+to|i\s+want\s+you\s+to)\s+/i,
  /^(?:go\s+ahead\s+and|kindly|just)\s+/i,
  /^(?:hey\s+)?(?:jarvis|assistant)\s+/i
];

const PHRASE_REPLACEMENTS = [
  { from: /\bturn it up\b/g, to: 'increase volume' },
  { from: /\bturn it down\b/g, to: 'decrease volume' },
  { from: /\bmake it louder\b/g, to: 'increase volume' },
  { from: /\bmake volume louder\b/g, to: 'increase volume' },
  { from: /\braise volume\b/g, to: 'increase volume' },
  { from: /\bvolume higher\b/g, to: 'increase volume' },
  { from: /\bmake it quieter\b/g, to: 'decrease volume' },
  { from: /\blower volume\b/g, to: 'decrease volume' },
  { from: /\bvolume lower\b/g, to: 'decrease volume' },
  { from: /\bmake it brighter\b/g, to: 'increase brightness' },
  { from: /\braise brightness\b/g, to: 'increase brightness' },
  { from: /\bbrightness higher\b/g, to: 'increase brightness' },
  { from: /\bmake it dimmer\b/g, to: 'decrease brightness' },
  { from: /\blower brightness\b/g, to: 'decrease brightness' },
  { from: /\bbrightness lower\b/g, to: 'decrease brightness' },
  { from: /\bshut down\b/g, to: 'shutdown' },
  { from: /\bclose down\b/g, to: 'close' },
  { from: /\bexit out of\b/g, to: 'close' },
  { from: /\bget rid of\b/g, to: 'close' },
  { from: /\blook for\b/g, to: 'find' },
  { from: /\bsearch up\b/g, to: 'search for' },
  { from: /\bsearch about\b/g, to: 'search for' },
  { from: /\bgoogle about\b/g, to: 'google' },
  { from: /\bclick first\b/g, to: 'click the first' },
  { from: /\bopen first\b/g, to: 'open the first' },
  { from: /\bwhere i the\b/g, to: 'where is the' },
  { from: /\bwhere i\b/g, to: 'where is' },
  { from: /\bopen up\b/g, to: 'open' },
  { from: /\bbring up\b/g, to: 'open' },
  { from: /\bpull up\b/g, to: 'open' },
  { from: /\bfire up\b/g, to: 'open' },
  { from: /\bbring to front\b/g, to: 'switch to' },
  { from: /\bswitch over to\b/g, to: 'switch to' },
  { from: /\bput on\b/g, to: 'play' },
  { from: /\bstart playing\b/g, to: 'play' },
  { from: /\bplay me\b/g, to: 'play' },
  { from: /\bqueue up\b/g, to: 'play' },
  { from: /\bdo not do it\b/g, to: 'cancel' },
  { from: /\bdont do it\b/g, to: 'cancel' },
  { from: /\bforget it\b/g, to: 'cancel' },
  { from: /\bleave it\b/g, to: 'cancel' },
  { from: /\bnever mind\b/g, to: 'cancel' },
  { from: /\bfull screen\b/g, to: 'fullscreen' },
  { from: /\bminimise\b/g, to: 'minimize' },
  { from: /\bmaximise\b/g, to: 'maximize' },
  { from: /\bunpause\b/g, to: 'resume' },
  { from: /\bcarry on\b/g, to: 'resume' },
  { from: /\bnexr\b/g, to: 'next' },
  { from: /\bsony\b/g, to: 'song' },
  { from: /\bweb site\b/g, to: 'website' },
  { from: /\bapplemusic\b/g, to: 'apple music' },
  { from: /\bscreen shot\b/g, to: 'screenshot' },
  { from: /\btake picture of screen\b/g, to: 'take screenshot' },
  { from: /\bcapture the screen\b/g, to: 'capture screen' }
];

const TOKEN_CORRECTIONS = {
  activte: 'activate',
  apllication: 'application',
  applcation: 'application',
  brighness: 'brightness',
  capatin: 'captain',
  caption: 'captain',
  captin: 'captain',
  capitol: 'capital',
  calender: 'calendar',
  calandr: 'calendar',
  calenders: 'calendars',
  cancle: 'cancel',
  canle: 'cancel',
  cancl: 'cancel',
  cloe: 'close',
  clos: 'close',
  clouse: 'close',
  cloth: 'close',
  clothes: 'close',
  cloze: 'close',
  clsoe: 'close',
  clint: 'client',
  cloudfare: 'cloudflare',
  cloudfair: 'cloudflare',
  crome: 'chrome',
  crom: 'chrome',
  cheom: 'chrome',
  decrese: 'decrease',
  developement: 'development',
  deveopemt: 'development',
  devlopement: 'development',
  devlopemt: 'development',
  develpment: 'development',
  discordd: 'discord',
  documants: 'documents',
  dont: 'do not',
  dowloads: 'downloads',
  downlodes: 'downloads',
  downolades: 'downloads',
  downolads: 'downloads',
  exitt: 'exit',
  firefix: 'firefox',
  foldr: 'folder',
  increse: 'increase',
  lauch: 'launch',
  lnauch: 'launch',
  mesage: 'message',
  musc: 'music',
  musci: 'music',
  mozila: 'mozilla',
  notpad: 'notepad',
  opne: 'open',
  noopen: 'open',
  playbak: 'playback',
  quik: 'quick',
  rose: 'close',
  seach: 'search',
  serch: 'search',
  searh: 'search',
  saerch: 'search',
  serach: 'search',
  screencap: 'screenshot',
  screenshort: 'screenshot',
  screenshorts: 'screenshots',
  screeshot: 'screenshot',
  screnshot: 'screenshot',
  scrnshot: 'screenshot',
  si: 'is',
  spoitfy: 'spotify',
  applemusic: 'apple music',
  swtich: 'switch',
  teh: 'the',
  teems: 'teams',
  telgram: 'telegram',
  teligram: 'telegram',
  teigam: 'telegram',
  timr: 'timer',
  tommorow: 'tomorrow',
  volum: 'volume',
  vol: 'volume',
  whatsap: 'whatsapp',
  whare: 'where',
  whre: 'where',
  youtub: 'youtube',
  yotube: 'youtube',
  yotub: 'youtube',
  chrmoe: 'chrome',
  chmo: 'chrome',
  chrm: 'chrome',
  chrom: 'chrome'
};

const TOKEN_SEQUENCE_REPLACEMENTS = [
  { from: ['whare', 'i'], to: ['where', 'is'] },
  { from: ['where', 'i'], to: ['where', 'is'] },
  { from: ['whre', 'i'], to: ['where', 'is'] },
  { from: ['what', 'sap'], to: ['whatsapp'] },
  { from: ['what', 'sapp'], to: ['whatsapp'] },
  { from: ['you', 'tube'], to: ['youtube'] },
  { from: ['micro', 'soft'], to: ['microsoft'] }
];

const DOMAIN_VOCABULARY = [
  'alarm',
  'application',
  'app',
  'battery',
  'brightness',
  'browser',
  'bring',
  'calendar',
  'captain',
  'chrome',
  'screenshots',
  'quick',
  'clock',
  'close',
  'copy',
  'cpu',
  'create',
  'delete',
  'desktop',
  'directory',
  'disk',
  'day',
  'date',
  'documents',
  'downloads',
  'edge',
  'erase',
  'excel',
  'file',
  'find',
  'folder',
  'google',
  'help',
  'chatgpt',
  'gpt',
  'claude',
  'gemini',
  'perplexity',
  'launch',
  'link',
  'links',
  'lunch',
  'lock',
  'memory',
  'minimize',
  'move',
  'music',
  'mute',
  'navigate',
  'news',
  'notepad',
  'open',
  'outlook',
  'paint',
  'pdf',
  'pdfs',
  'pictures',
  'processes',
  'ram',
  'remind',
  'reminder',
  'remove',
  'rename',
  'restart',
  'result',
  'results',
  'run',
  'search',
  'screenshot',
  'capture',
  'take',
  'score',
  'settings',
  'shutdown',
  'sleep',
  'spotify',
  'status',
  'switch',
  'team',
  'teams',
  'winner',
  'winners',
  'champion',
  'champions',
  'capital',
  'cricket',
  'india',
  'indian',
  'ipl',
  'suv',
  'timer',
  'time',
  'unmute',
  'url',
  'videos',
  'volume',
  'website',
  'window',
  'word',
  'youtube',
  'zoom',
  'queue',
  'play',
  'song',
  'songs',
  'music',
  'track',
  'tracks',
  'media',
  'playback',
  'next',
  'previous',
  'prev',
  'pause',
  'resume',
  'skip',
  'continue',
  'unpause',
  'fullscreen',
  'full',
  'screen',
  'watch'
];

module.exports = {
  DOMAIN_VOCABULARY,
  FILLER_WORDS,
  LEAD_IN_PATTERNS,
  PHRASE_REPLACEMENTS,
  TOKEN_CORRECTIONS,
  TOKEN_SEQUENCE_REPLACEMENTS
};
